In [1]:
pip install sqlalchemy 

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas

In [5]:
pip install Matplotlib

Note: you may need to restart the kernel to use updated packages.


In [7]:
import pandas as pd

In [13]:
data = pd.read_csv('SVMtrain.csv')

In [15]:
import numpy as np

In [17]:
survived = np.array(data.Survived)

In [19]:
survived

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [21]:
data

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    Male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    Male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
884          887         0       2    Male  27.0      0      0  13.0000   
885          888         1       1  female  19.0      0      0  30.0000   
886          889         0       3  female  60.0      1      2  23.4500   
887          890         1       1    Male  26.0      0      0  30.0000   
888          891         0       3    Male  32.0      0      0   7.7500   

     Embarked  
0           3  
1           1  
2           3  
3           3  
4           3  
..        ...  
884         3  
885         3  
886         3  
887         1  
888         2  

[889 rows x 9 columns]

In [23]:
survivors = np.sum(survived)

In [25]:
survivors

340

In [27]:
passenger_data = np.array(data[['Age', 'Fare']])

In [29]:
passenger_data

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [60.    , 23.45  ],
       [26.    , 30.    ],
       [32.    ,  7.75  ]])

In [31]:
sorted_passenger_data = passenger_data[passenger_data[:, 0].argsort()]

In [33]:
sorted_passenger_data

array([[ 0.42  ,  8.5167],
       [ 0.67  , 14.5   ],
       [ 0.75  , 19.2583],
       ...,
       [71.    , 49.5042],
       [74.    ,  7.775 ],
       [80.    , 30.    ]])

In [35]:
sorted_passenger_data.head(80)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [37]:
passenger1 = data.loc[np.argmin(data['Age'])]

In [39]:
passenger1

PassengerId       804
Survived            1
Pclass              3
Sex              Male
Age              0.42
SibSp               0
Parch               1
Fare           8.5167
Embarked            1
Name: 802, dtype: object

In [41]:
passenger2 = data.loc[np.argmax(data['Age'])]

In [45]:
print(passenger1)
print(passenger2)

PassengerId       804
Survived            1
Pclass              3
Sex              Male
Age              0.42
SibSp               0
Parch               1
Fare           8.5167
Embarked            1
Name: 802, dtype: object
PassengerId     631
Survived          1
Pclass            1
Sex            Male
Age            80.0
SibSp             0
Parch             0
Fare           30.0
Embarked          3
Name: 629, dtype: object


In [47]:
family = np.array(data[['SibSp', 'Parch']])

In [49]:
family

array([[1, 0],
       [1, 0],
       [0, 0],
       ...,
       [1, 2],
       [0, 0],
       [0, 0]], dtype=int64)

In [51]:
sorted_family = family[family[:, 0].argsort()]

In [53]:
sorted_family

array([[0, 2],
       [0, 2],
       [0, 0],
       ...,
       [8, 2],
       [8, 2],
       [8, 2]], dtype=int64)

In [55]:
rodstvennikixd = np.sum(family)

In [57]:
rodstvennikixd

806

In [59]:
morerodstvenniki = np.argmax(np.sum(family, axis=1))

In [63]:
dudemorerodstvenniki = data.loc[morerodstvenniki]

In [65]:
dudemorerodstvenniki

PassengerId      160
Survived           0
Pclass             3
Sex             Male
Age             60.0
SibSp              8
Parch              2
Fare           69.55
Embarked           3
Name: 158, dtype: object